name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate .env file
        run: cp .env.example .env
        shell: bash

      - name: Build the Docker image
        run: docker-compose build outgo
        shell: bash
